apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: terraform-aws-vpc
  description: Terraform module for creating VPCs in Amazon Web Services
  annotations:
    github.com/project-slug: honestbank/terraform-aws-vpc
    github.com/team-slug: honestbank/devops-engineers
spec:
  type: tf-module
  lifecycle: prod
  system: infrastructure
  owner: group:devops-engineers
  dependencyOf:
    - resource:network-infrastructure
